"""berita table

Revision ID: 0b9ccde0974f
Revises: 
Create Date: 2022-09-14 23:17:47.320920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9ccde0974f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berita_model',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('waktu_tayang', sa.BigInteger(), nullable=False),
    sa.Column('konten', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('berita_model')
    # ### end Alembic commands ###
